version: '3'
services:
  charlie-mnemonic:
    image: goodaidev/charlie-mnemonic:latest
    container_name: charlie-mnemonic
    hostname: charlie-mnemonic
    entrypoint: [ "python", "launcher.py" ]
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEPLOY_ENV=local
      - HOST=0.0.0.0
      - PORT=8002
      - CHARLIE_MNEMONIC_USER_DIR=${CHARLIE_USER_DIR}
    ports:
      - "8002:8002"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CHARLIE_USER_DIR}:/app/users
    env_file:
      - .env
    privileged: true

  psdb:
    image: postgres:14
    container_name: psdb
    hostname: psdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOSTNAME=psdb
      - PGGSSENCMODE=disable

  python-env:
    build:
      context: ./pythondocker
      dockerfile: Dockerfile
    container_name: charlie-mnemonic-python-env
    hostname: charlie-mnemonic-python-env
    volumes:
      - ${CHARLIE_USER_DIR}:/data

volumes:
  postgres-data:
